config/routes.rb
Rails.application.routes.draw do

  # * Friends controller routes without using resources

  # get "/friends/", to: "friends#index", as: "friends"
  # post "/friends/", to: "friends#create"
  # delete "/friends/:id", to: "friends#destroy", as: "friend"

  # * Generated Groups controller routes using resources

  # get 'groups/index'
  # get 'groups/new'
  # get 'groups/create'
  # get 'groups/destroy'
  # get 'groups/add_user'
  # get 'groups/create_user'
  # get 'groups/destroy_user'
  get "search_user_to_invite", to: "orders#search"
  get "add_user_to_invited_list", to: "orders#addToInvitedList"
  get "remove_user_from_invited_list", to: "orders#removeFromInvitedList"
  get "user_accepte_to_join_order", to: "orders#joinOrder"
  get "user_refuse_to_join_order", to: "orders#cancelInvitaion"
  # for invited and joined users
  get 'orders/:order_id/invited', :to => 'orders#order_Invited', as: "order_invited"
  get 'orders/:order_id/joined', :to => 'orders#order_Joined', as: "order_joined"
  get 'orders/:order_id/joined', :to => redirect('/order_joined.html.erb')
  get 'orders/:order_id/invited', :to => redirect('/order_invited.html.erb')

  # for removing users from order
  get 'orders/:order_id/joined/:invited_id', :to => 'orders#remove_Joined', as: "remove_joined"
  get 'orders/:order_id/invited/:invited_id', :to => 'orders#remove_Invited', as: "remove_invited"



  resources :friends
  resources :groups do
    get "/user", to: "groups#add_user", as: "add_user"
    post "/user", to: "groups#create_user", as: "create_user"
    delete "/user/:user_id", to: "groups#destroy_user", as: "destroy_user"
    get "search_user", to: "groups#search"
  end

  # * resource for notification
  resources :notifications

  # * resource for order
  resources :orders do
    resources :order_members
  end

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  authenticated :user do
    root "pages#home", as: "authenticated_root"
  end

  devise_scope :user do
    root "devise/sessions#new"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    @friends = current_user.friends
  end

  def create
    candidate_friend = User.find_by email: params[:email]
    # * user exists
    if candidate_friend
      candidate_friend_instance = Friendship.new friend_id: candidate_friend.id, user_id: current_user.id
      # * user is valid
      if candidate_friend_instance.save
        new_friend = {
          id: candidate_friend.id,
          full_name: candidate_friend.full_name,
          image: candidate_friend.get_image(),
          email: candidate_friend.email,
        }
        res = {
          success: true,
          new_friend: new_friend,
        }
        render json: res.to_json
      else
        res = {
          success: false,
          errors: candidate_friend_instance.errors[:user_id].first,
        }
        render json: res.to_json
      end
    else
      res = {
        success: false,
        errors: "User doesn't exist",
      }
      render json: res.to_json
    end
  end

  def destroy
    friend = User.find(params[:id])
    @friend_name = friend.full_name 
    @friend_id = params[:id]
    @friendship_record = Friendship.where(friend_id: params[:id], user_id: current_user.id).first
    @friendship_record.destroy
    respond_to do |format|
      format.js { render partial: "javascripts/friends/destroy_friend" }
    end
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<div class="card mt-5">
  <div class="card-header text-center">
    <h3><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16"><path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/><path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
      </svg> Add a Friend</h3>
  </div>
  <div class="card-body">
    <%= form_with model: friend, remote: true do |form| %>
      <div class="row justify-content-center">
        <div class="col-md-10">
          <%= form.email_field :email, class: "form-control", placeholder: "Write an email to add friend" %>
        </div>
        <div class="col-md-1">
          <input type="submit" class="btn btn" id="friends-add-btn" style="background-color: #FF5A01; color: white" value="Add">
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/friends/index.html.erb
<%= render "friends/form", friend: @friend %>
<div class="card mt-5">
  <div class="card-header text-center">
    <h3><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-person-lines-fill" viewBox="0 0 16 16">
        <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm-5 6s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zM11 3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5zm.5 2.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1h-4zm2 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-2zm0 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-2z"/>
      </svg> Friends List</h3>
  </div>
  <div class="card-body">
    <div class="row " style="top:0%, left:0%">
      <div class="col-md-10 row overflow-auto m-auto mt-5" id="friends-container" style="top: 0%; left: 0%; max-height: 350px;">

        <% for friend in @friends %>
          <div id="friend-<%= friend.id %>" class="col-md-4">
            <div class="row" style="top:0%, left:0%">
              <div class="card mx-5 my-3">
                <div class="card-body">
                  <div class="col-md-6">
                    <%= image_tag friend.get_image, style: "height:120px;width:120;" %>
                  </div>
                  <div class="col-md-12">
                    <br>
                    <h4>
                      <div class="badge badge-light"> <%= friend.full_name %></div>
                    </h4>
                    <hr/>
                    <div class="btn btn-danger btn-sm"> <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-x" viewBox="0 0 16 16"><path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/><path fill-rule="evenodd" d="M12.146 5.146a.5.5 0 0 1 .708 0L14 6.293l1.146-1.147a.5.5 0 0 1 .708.708L14.707 7l1.147 1.146a.5.5 0 0 1-.708.708L14 7.707l-1.146 1.147a.5.5 0 0 1-.708-.708L13.293 7l-1.147-1.146a.5.5 0 0 1 0-.708z"/></svg>
                      <%= link_to "unfriend", friend_path(friend), style: "color: white", method: :delete, data: { confirm: "Are you sure?" }, remote: true %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag "friends/add_friend" %>