config/routes.rb
Rails.application.routes.draw do

  # * Friends controller routes without using resources

  # get "/friends/", to: "friends#index", as: "friends"
  # post "/friends/", to: "friends#create"
  # delete "/friends/:id", to: "friends#destroy", as: "friend"

  # * Generated Groups controller routes using resources

  # get 'groups/index'
  # get 'groups/new'
  # get 'groups/create'
  # get 'groups/destroy'
  # get 'groups/add_user'
  # get 'groups/create_user'
  # get 'groups/destroy_user'
  get "search_user_to_invite", to: "orders#search"
  get "add_user_to_invited_list", to: "orders#addToInvitedList"
  get "remove_user_from_invited_list", to: "orders#removeFromInvitedList"
  get "user_accepte_to_join_order", to: "orders#joinOrder"
  get "user_refuse_to_join_order", to: "orders#cancelInvitaion"
  # for invited and joined users
  get 'orders/:order_id/invited', :to => 'orders#order_Invited', as: "order_invited"
  get 'orders/:order_id/joined', :to => 'orders#order_Joined', as: "order_joined"
  get 'orders/:order_id/joined', :to => redirect('/order_joined.html.erb')
  get 'orders/:order_id/invited', :to => redirect('/order_invited.html.erb')

  # for removing users from order
  get 'orders/:order_id/joined/:invited_id', :to => 'orders#remove_Joined', as: "remove_joined"
  get 'orders/:order_id/invited/:invited_id', :to => 'orders#remove_Invited', as: "remove_invited"



  resources :friends
  resources :groups do
    get "/user", to: "groups#add_user", as: "add_user"
    post "/user", to: "groups#create_user", as: "create_user"
    delete "/user/:user_id", to: "groups#destroy_user", as: "destroy_user"
    get "search_user", to: "groups#search"
  end

  # * resource for notification
  resources :notifications

  # * resource for order
  resources :orders do
    resources :order_members
  end

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  authenticated :user do
    root "pages#home", as: "authenticated_root"
  end

  devise_scope :user do
    root "devise/sessions#new"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  # * Relationship with owner (One to Many)
  belongs_to :owner, class_name: "User"
  # * Relationship with members (Many to Many)
  # has_many :users, :through => :groups_users
  # has_many :groups_users
  has_many :group_participants, dependent: :destroy

    # has_many :groups_users, class_name: "GroupsUser", dependent: :destroy
  # has_and_belongs_to_many :users ,    :through => :groups_users ,dependent: :delete_all


  # * Relationship with groups-users ownership
  # has_many :groups_users, dependent: :delete_all

  validates :name, presence: true, uniqueness: true
  # validate :members_uniqness, :friends_only

  def members_uniqness
    errors.add(:user, "You cannot repeat a member in a group.") unless user_ids.uniq == user_ids
  end

  def friends_only
    owner = User.find owner_id
    user_ids.each { |user_id|
      if user_id == owner_id
        errors.add(:owner, "You cannot add yourself to your own group.")
      else
        user = User.find user_id
        errors.add(:user, "##{user.id} #{user.full_name} is not in your friend list") unless owner.friend_with? user_id
      end
    }
  end

  def group_member?(id_of_member)
    self.group_participants.where(user_id: id_of_member).exists?
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups.all
    @group = Group.new
  end

  def new
  end

  def create
    @group = Group.new(group_params.merge(owner_id: current_user.id))

    if @group.save
      redirect_to groups_path
    else
      @groups = current_user.groups.all
      render :index
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

  def add_user
    @groups = current_user.groups.all
    @selected_group_id = params[:group_id]
    @selected_group = Group.find @selected_group_id
    @members = Group.find(@selected_group_id).group_participants.all.map { |group_participant| group_participant.user }
    @member = current_user.groups.find(@selected_group_id).group_participants.new
    @group = Group.new
  end

  def create_user
    @member = User.find(params[:user])
    @member = GroupParticipant.new({ "user_id" => @member.id, "group_id" => params[:group_id] })
    if @member.save
      @member = User.find(params[:user])
      respond_to do |format|
        format.js { render partial: "javascripts/groups/create_user" }
      end
    end
  end

  def destroy_user
    GroupParticipant.delete_by(user_id: params[:user_id], group_id: params[:group_id])
    @member_id = params[:user_id]
    respond_to do |format|
      format.js { render partial: "javascripts/groups/destroy_user" }
    end
    # * Or you can write it in this way, it's basically the same
    # render js: id if params[:format] == "js"
  end

  def search
    if params[:user].present?
      @group = current_user.groups.find(params[:group_id])
      @members = current_user.search(params[:user])
      if @members
        respond_to do |format|
          format.js { render partial: "javascripts/groups/member_result" }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "User is not in your friendlist"
          format.js { render partial: "javascripts/groups/member_result" }
        end
      end
    else
      respond_to do |format|
        @group = current_user.groups.find(params[:group_id])
        @members = []
        flash.now[:alert] = "Please enter a friend name or email to search"
        format.js { render partial: "javascripts/groups/member_result" }
      end
    end
  end

  private

  def group_params
    params.require(:group).permit(:name)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_added_member.html.erb
<div class="col-md-4" id="<%= @member.id %>">
  <div class="row" style="top:0%, left:0%">
    <div class="card mx-6 my-4">
      <div class="card-body">
        <div class="col-md-6">
          <%= image_tag @member.get_image, style: "height:80px;width:80;" %>
        </div>
        <div class="col-md-6">
          <br>
          <h5>
            <div class="badge badge-light"><%= @member.full_name %></div>
          </h5>
          <hr/>
          <div class="btn btn-danger btn-sm">
            <%= link_to "Remove", group_destroy_user_path(user_id: @member.id), :method => "delete", style: "color:white", data: { confirm: "Are you sure?" }, remote: true %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/_form.html.erb
<div class="card mt-3">
  <div class="card-header text-center">
    <h3>
      <i class="bi bi-people-fill"></i>
      Add a new Group
    </h3>
  </div>
  <div class='text-center'>
    <% @group.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <%= form_with model: @group do |form| %>
    <div class="d-flex g-3 justify-content-sm-center mt-5 mb-5">
      <div class="col-9 align-self-center m-2">
        <%= form.text_field :name, class: "form-control", placeholder: "Enter a group name to add", autofocus: true %>
      </div>
      <div class="col-1 align-self-center">
        <%= form.submit "Add", class: "btn btn", style: "background-color: #FF5A01; color: white" %>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/_group.html.erb
<div class="row">
  <div class="col-md-8">
    <h5><%= group.name %></h5>
  </div>
  <div class="col-md-2">
    <%= link_to '<h2><i class="bi bi-person-plus-fill"></i></h2>'.html_safe, group_add_user_path(group), class: "a_group" %>
  </div>
  <div class="col-md-2">
    <%= link_to '<h2><i class="bi bi-trash"></i></h2>'.html_safe, group, method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
</div>
<hr/>

app/views/groups/_member_result.html.erb
<% @members.each do |member| %>
  <% if current_user.friend_with?(member.id) && !@group.group_member?(member.id) %>
    <div class="col-md-2">
      <% if member.image? %>
        <%= image_tag member.get_image, style: "height:50px;width:50;" %>
      <% end %>
    </div>
    <div class="col-md-4">
      <strong> Name: </strong> <span> <%= member.full_name %></span>
    </div>
    <div class="col-md-5">
      <strong> Email: </strong> <span> <%= member.email %></span>
    </div>
    <div class="col-md-1">
      <%= link_to "Add", group_create_user_path(user: member), class: "btn btn-sm btn-success", method: :post, remote: true %>
    </div>
  <% end %>
  <hr/>
  <hr/>
<% end %>

app/views/groups/add_user.html.erb
<style>
  .card-custom {
    background-color: #FF5A01;
    color: white;
  }
  .xy{color:white}
</style>

<%# -----------------------Creating a Group Form----------------------- %>
<%= render "form" %>

<%# -----------------------Showing Current User Groups----------------------- %>
<div class="row">
  <div class="col-sm-4 mb-3 mt-4">
    <div class="card bg-light">
      <h3>
        <div class="card-header card-custom text-center">My Groups</div>
      </h3>
      <div class="card-body">
        <%= render @groups %>
      </div>
    </div>
  </div>

  <%# -----------------------Selecting a Group----------------------- %>
  <div class="col-sm-8 mb-3 mt-4">
    <div class="card bg-light">
      <h3>
        <div class="card-header card-custom text-center"><%= @selected_group.name %></div>
      </h3>

      <%= form_tag group_search_user_path, remote: true, method: :get do %>

        <div class="form-group d-flex justify-content-between">
          <div class="col-3 align-self-center m-auto">
            <%= label :name, "Add a Friend to Group", class: "col-form-label fw-bold" %>
          </div>
          <div class="col-sm-8 m-2 align-self-center">
            <%= text_field_tag :user, params[:user], placeholder: "Enter a name / email to add it to this group", autofocus: true, class: "form-control" %>
          </div>
          <div class="col-2 align-self-center m-auto d-none">
            <input type="submit" value="Search" class="btn btn-success btn-lg" id="btn-img">
          </div>
        </div>
      <% end %>

      <%# -----------------------Searched Members Results----------------------- %>
      <div class="row" style="top:0%, left:0%">
        <div class="col-md-10 row overflow-auto m-auto mt-5" style="top: 0%; left: 0%; max-height: 350px;" id="search-results">
        </div>
      </div>
      <%# -----------------------Selected Group Members----------------------- %>
      <div class="row" style="top:0%, left:0%">
        <div class="col-md-10 row overflow-auto m-auto mt-5" style="top: 0%; left: 0%; max-height: 350px;" id="member-results">
          <% @members.each do |member| %>
            <div class="col-md-4" id="<%= member.id %>">
              <div class="row" style="top:0%, left:0%">
                <div class="card mx-6 my-4">
                  <div class="card-body">
                    <div class="col-md-6">
                      <%= image_tag member.get_image, style: "height:80px;width:80;" %>
                    </div>
                    <div class="col-md-6">
                      <br>
                      <h5>
                        <div class="badge badge-light"><%= member.full_name %></div>
                      </h5>
                      <hr/>
                      <div class="btn btn-danger btn-sm">
                        <%= link_to "Remove", group_destroy_user_path(user_id: member.id), :method => "delete", style: "color:white", data: { confirm: "Are you sure?" }, remote: true %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>

      <%# -----------------------Including app/javascript/packs/ js files----------------------- %>
      <%= javascript_pack_tag "groups/add_user" %>

app/views/groups/create_user.js.erb
console.log("Inside create_user.js.erb");

$('#user').val('');
$('#search-results').html('');
$('#member-results').prepend('<%= j render "groups/added_member.html" %>');
$('#<%= @member.id %>').hide().fadeIn(1000);

app/views/groups/destroy_user.js.erb
$("#<%= @member_id %>").fadeOut(500, function () {
  $(this).remove();
});

app/views/groups/index.html.erb
<%= render "form" %>

<style>
  .card-custom {
    background-color: #FF5A01;
    color: white;
  }
  .xy{color:white}
</style>

<div class="row">

  <div class="col-sm-4 mb-3 mt-4">
    <div class="card bg-light">
      <h3>
        <div class="card-header card-custom">My Groups</div>
      </h3>
      <div class="card-body">
        <%= render @groups %>
      </div>
    </div>
  </div>