config/routes.rb
Rails.application.routes.draw do

  # * Friends controller routes without using resources

  # get "/friends/", to: "friends#index", as: "friends"
  # post "/friends/", to: "friends#create"
  # delete "/friends/:id", to: "friends#destroy", as: "friend"

  # * Generated Groups controller routes using resources

  # get 'groups/index'
  # get 'groups/new'
  # get 'groups/create'
  # get 'groups/destroy'
  # get 'groups/add_user'
  # get 'groups/create_user'
  # get 'groups/destroy_user'
  get "search_user_to_invite", to: "orders#search"
  get "add_user_to_invited_list", to: "orders#addToInvitedList"
  get "remove_user_from_invited_list", to: "orders#removeFromInvitedList"
  get "user_accepte_to_join_order", to: "orders#joinOrder"
  get "user_refuse_to_join_order", to: "orders#cancelInvitaion"
  # for invited and joined users
  get 'orders/:order_id/invited', :to => 'orders#order_Invited', as: "order_invited"
  get 'orders/:order_id/joined', :to => 'orders#order_Joined', as: "order_joined"
  get 'orders/:order_id/joined', :to => redirect('/order_joined.html.erb')
  get 'orders/:order_id/invited', :to => redirect('/order_invited.html.erb')

  # for removing users from order
  get 'orders/:order_id/joined/:invited_id', :to => 'orders#remove_Joined', as: "remove_joined"
  get 'orders/:order_id/invited/:invited_id', :to => 'orders#remove_Invited', as: "remove_invited"



  resources :friends
  resources :groups do
    get "/user", to: "groups#add_user", as: "add_user"
    post "/user", to: "groups#create_user", as: "create_user"
    delete "/user/:user_id", to: "groups#destroy_user", as: "destroy_user"
    get "search_user", to: "groups#search"
  end

  # * resource for notification
  resources :notifications

  # * resource for order
  resources :orders do
    resources :order_members
  end

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  authenticated :user do
    root "pages#home", as: "authenticated_root"
  end

  devise_scope :user do
    root "devise/sessions#new"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  # Relationship with User
  belongs_to :user

  # Relationship with order_member
  has_many :order_members, :dependent => :destroy

  # Relationship with invited member
  has_many :invited_members, :dependent => :destroy
  
  # Relationship with invited member
  has_many :notifications, dependent: :destroy

  # has_one_attached :menu_img
end

app/controllers/orders_controller.rb
require 'active_record/errors'
class OrdersController < ApplicationController


  #TODO landing page (orders ana 4arekt feha aw ana el 3amaltha)
  #TODO orders page (el orders el ana 3mltha bc)
  #TODO nms7 GroupsUser model + GroupMember Model 
  #TODO el profile picture bta3t el user 
  #TODO el docker 
  #TODO notification for orders 
  #TODO el notifications el mafrod mttms74
  def index
    # @orders = Order.where(user_id: current_user.id)
    @orders = Order.where(user: current_user).or(Order.where(user: current_user.friends))
  end

  def show
    begin
      @order = Order.find(params[:id])
      @Items = OrderMember.where(order: @order)
      @invited = InvitedMember.where(order_id: @order.id).count
      @joind = InvitedMember.where(joind: true).where(order_id: @order.id).count
    rescue => e 
      raise AbstractController::ActionNotFound.new("Sorry this order is deleted")
    end 
  end

  def new
    @order = Order.new
    InvitedUsers.clear()
    @friends_to_invite = InvitedUsers.get()
  end

  def create
    @order = Order.new(order_params)
    friends_to_invite = InvitedUsers.get()
    if @order.save
      friends_to_invite.each do |user|
        userModel = User.find(user.id)
        invitedMember = InvitedMember.create(order: @order, user: userModel, joind: false)
        Notification.notify_invite(invitedMember)
      end
      redirect_to @order
    else
      render :new
    end
  end

  def update
    @order = Order.find(params[:id])
    @order.status = "Finish"
    @order.save
    respond_to do |format|
      format.js { render partial: "javascripts/orders/finish_order" }
    end
  end
  
  def search
    if params[:user].present?
      # @group = current_user.groups.find(params[:group_id])
      @members = current_user.search(params[:user])
      puts(current_user.groups)
      puts("------------------------------user group--------------------------")
      @group = current_user.groups.where(name: params[:user]).limit(1)
      puts(@group)
      puts("------------------------------chossen group--------------------------")
      if @group != []
        @members = @group[0].group_participants.all.map { |group_participant| group_participant.user }
        if @members
          puts("---------------render groups--------------------")
          respond_to do |format|
            format.js { render partial: "javascripts/orders/search_result" }
          end
        end  
      elsif @members != []
        puts(@members)
        puts("---------------render members--------------------")
        respond_to do |format|
          format.js { render partial: "javascripts/orders/search_result" }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "User is not in your friendlist"
          format.js { render partial: "javascripts/orders/search_result" }
        end
      end
    else
      respond_to do |format|
        @group = current_user.groups.find(params[:group_id])
        @members = []
        flash.now[:alert] = "Please enter a friend name or email to search"
        format.js { render partial: "javascripts/orders/search_result" }
      end
    end
  end

  def addToInvitedList
    if params[:user].present?
      InvitedUsers.add(User.find(params[:user]))
      puts(InvitedUsers.get())
      @friends_to_invite = InvitedUsers.get()
      render partial: "javascripts/orders/invitation_list"
    end
  end

  def removeFromInvitedList
    if params[:user].present?
      InvitedUsers.delete(User.find(params[:user]))
      puts(InvitedUsers.get())
      @friends_to_invite = InvitedUsers.get()
      render partial: "javascripts/orders/invitation_list"
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    respond_to do |format|
      format.js { render partial: "javascripts/orders/cancel_order" }
    end
  end

  def order_Invited
    @order = Order.find(params[:order_id])
    @invited_users = InvitedMember.where(order_id: @order.id).where(joind: false)
  end

  def order_Joined
    @order = Order.find(params[:order_id])
    @joined_users = InvitedMember.where(order_id: @order.id).where(joind: true)
  end

  def remove_Invited
    @id = params[:invited_id] 
    invited_member = InvitedMember.find(@id)
    invited_member.destroy
    respond_to do |format|
      format.js { render partial: "javascripts/orders/remove_user" }
    end
  end

  def remove_Joined
    @order = Order.find(params[:order_id])
    @id = params[:invited_id] 
    invited_member = InvitedMember.find(@id)
    invited_member.destroy
    order_member = @order.order_members.where(user_id: invited_member.user_id)
    order_member.each do |item|
      item.destroy
    end
    respond_to do |format|
      format.js { render partial: "javascripts/orders/remove_user" }
    end
  end

  def joinOrder
    puts(params)
    @user = User.find(params[:user])
    @order = Order.find(params[:order])
    notification = Notification.find(params[:notification_id])
    invitedMember = InvitedMember.find_by(user: @user, order: @order)
    puts(invitedMember)
    notification.destroy
    if @order.status != "Active"
      raise AbstractController::ActionNotFound.new('Sorry this order is finished!')
    end
    if invitedMember == nil
      raise AbstractController::ActionNotFound.new('Sorry you are no longer invited to this order or this order is deleted!')
    end
    if invitedMember != nil and @order.status == "Active"
      invitedMember.update(joind: true)
      Notification.notify_accept(@order, @user)
    end
    redirect_to @order
  end

  def cancelInvitaion
    puts(params)
    @user = User.find(params[:user])
    @order = Order.find(params[:order])
    notification = Notification.find(params[:notification_id])
    invitedMember = InvitedMember.find_by(user: @user, order: @order)
    puts(invitedMember)
    if invitedMember != nil
      invitedMember.destroy
    end
    notification.destroy
    redirect_to "/notifications"
  end

  private
    def order_params
      params.require(:order).permit(:mealtype, :resturant_name, :menu_img, :option, :joined_id, :invited_id).merge(user: current_user)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="row col-md-12">
  <div class="card  mt-5" style="width: 50%;">
      <div class="card-header text-center">
          <h3>
          <i class="bi bi-clipboard-plus"></i>
              Create Order
          </h3>
      </div>
      <div class="card-body">
          <%= form_with model: order do |form| %>
            <div class="form-group">
              <%= form.label :'order for', class:"col-sm-3 col-form-label" %>
              <%= form.select :mealtype, options_for_select(["Breakfast", "Launch", "Dinner", "Other"]), {}, {class: "form form-group form-control"}  %>
            </div>
            <div class="form-group">
              <%= form.label :restaurant_name %><br>
              <%= form.text_field :resturant_name, class:"form-control", placeholder: "Enter the restaurant name", required: true%>
              <% order.errors.full_messages_for(:resturant_name).each do |message| %>
                <div><%= message %></div>
              <% end %>
            </div>
            <div class="custom-file mt-3">
              <%= form.label :'Choose the menu image', class:"custom-file-label" %>
              <%= form.file_field :menu_img, class:"custom-file-input" %>
            </div>
            <%# <div> %>
              <%# <%= form.label :owner %>
              <%#= form.text_field :user, value: current_user,:readonly => true %> 
            <%# </div> %>
            <div class="mt-5">
              <%= form.submit :Submit, class:"btn btn-success btn-lg btn-block", style:"color:white" %>
            </div>
          <% end %>
      </div>
</div>
<%# -----------------------Selecting a Group----------------------- %>
  <div class="col-md-6 mt-6 mt-5">
    <div class="card bg-light" style="width: 110%;">
      <h3>
        <div class="card-header card-custom text-center">Invited Friends</div>
      </h3>

      <%= form_tag search_user_to_invite_path, remote: true, method: :get do %>
        <div class="row col-md-12 my-3">
          <div class="row mx-3">
            <%= label :name, "Invite Friends to this order", class: "col-form-label fw-bold" %>
          </div>
          <div class="row col">
            <%= text_field_tag :user, params[:user], placeholder: "Enter a name / email / group to invite", autofocus: true, class: "form-control" %>
          </div>
          <div class="row col-md-12 md-1 m-1 align-self-center m-auto d-none">
            <input type="submit" value="Search" class="btn btn-success btn-lg" id="btn-img">
          </div>
        </div>
      <% end %>

      <%# -----------------------Searched Members Results----------------------- %>
      <div class="row" style="top:0%, left:0%">
        <div class="col-md-10 row " style="top: 0%; left: 0%; max-height: 350px;" id="search-results"></div>
      </div>
      <%# -----------------------Selected Group Members----------------------- %>
      <div class="row" style="top:0%, left:0%">
        <div class="col-md-10 row overflow-auto m-auto mt-5" style="top: 0%; left: 0%; max-height: 350px;" id="invitation_list"></div>
      </div>

      <%# -----------------------Including app/javascript/packs/ js files----------------------- %>
      <%= javascript_pack_tag "orders/search_invited_user" %>
</div>
</div>

app/views/orders/_form_item.html.erb
<%= form_with(model: [ @order, @order.order_members.build ], local:false) do |form| %>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :Item %>
       <%= form.text_field :item, class:"form-control", placeholder: "Type the food item", :required => true %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :Amount %>
      <%= form.number_field :amount, min: 0, class:"form-control", :required => true %>
    </div>
  </div>
  <div class="form-row mt-1">
    <div class="form-group col-md-6">
      <%= form.label :Price %>
      <%= form.number_field :price, step: :any, min: 0, class:"form-control", :required => true %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :Comment %>
      <%= form.text_field :comment, class:"form-control", placeholder:"Type your comment" %>
    </div>
  </div>
  
  <button type="submit" class="btn btn-success btn-block mt-3">Add Item</button>
<% end %>

app/views/orders/_invitation_list.html.erb
<% @friends_to_invite.each do |member| %>
    <div class="col-md-4" id="<%= member.id %>">
      <div class="row" style="top:0%, left:0%">
        <div class="card mx-6 my-4">
          <div class="card-body">
            <div class="col-md-6">
              <%= image_tag member.get_image, style: "height:80px;width:80;" %>
            </div>
            <div class="col-md-6">
              <br>
              <h5>
                <div class="badge badge-light"><%= member.full_name %></div>
              </h5>
              <hr/>
              <div class="btn btn-danger btn-sm">
                <%= link_to "Remove", remove_user_from_invited_list_path(user: member), :method =>"get", style: "color:white", remote: true %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>

app/views/orders/_invited_member_result.html.erb
<% @members.each do |member| %>
<% if current_user.friend_with?(member.id) && !@group.group_member?(member.id) %>
    <div class="col-md-2">
    <% if member.image? %>
        <%= image_tag member.get_image, style: "height:50px;width:50;" %>
    <% end %>
    </div>
    <div class="col-md-4">
    <strong> Name: </strong> <span> <%= member.full_name %></span>
    </div>
    <div class="col-md-5">
    <strong> Email: </strong> <span> <%= member.email %></span>
    </div>
    <div class="col-md-1">
    <%= link_to "Add", add_user_to_invited_list_path(user: member), class: "btn btn-sm btn-success", method: :post, remote: true %>
    </div>
<% end %>
<hr/>
<hr/>
<% end %>

app/views/orders/_search_result.html.erb
<% @members.each do |member| %>
    <% if current_user.friend_with?(member.id) %>
        <div class="col-2 text-lift">
        <% if member.image? %>
            <%= image_tag member.get_image, style: "height:50px;width:50;" %>
        <% end %>
        </div>
        <div class="col-4 text-lift">
        <strong> Name: </strong> <span> <%= member.full_name %></span>
        </div>
        <div class="col-5 text-lift">
        <strong> Email: </strong> <span> <%= member.email %></span>
        </div>
        <div class="col-1 text-lift">
        <%= link_to "Add", add_user_to_invited_list_path(user: member), class: "btn btn-sm btn-success", method: :get, remote: true %>
        </div>
    <% end %>
    <hr/>
    <hr/>
<% end %>

app/views/orders/index.html.erb
<% #################################### %>
<div class="card mt-5">
  <div class="card-header text-center">
    <h3>
      <i class="bi bi-clipboard-check"></i>
      Orders
    </h3>
  </div>
  <div class="card-body">
    <%= button_to "Create new order", new_order_path, :method => "get", class: "btn btn-success btn-lg btn-block", style: "color:white" %>
  </div>
</div>

<% #################################### %>
<style>
  .thead-cusom{
    background-color: #FF5A01;
    color: white;
  }
</style>
<div class="card mt-4">
<table class="table text-center ">
  <thead class="thead-cusom">
    <tr>
      <th scope="col">Order</th>
      <th scope="col">Restaurante</th>
      <th scope="col">Invited</th>
      <th scope="col">Joined</th>
      <th scope="col">Status</th>
      <th scope="col" colspan="3">Action</th>
    </tr>
  </thead>
  <tbody>
   <% @orders.each do |order| %>

    <tr id="<%= order.id %>">
      <td><%= order.mealtype %></td>
      <td><%= order.resturant_name %></td>
      <td><%= order.invited_members.count %></td>
      <td><%= order.invited_members.where(joind: true).count %></td>
      <td class="status"><%= order.status %></td>
      <% if order.user == current_user && order.status == "Active" %>
        <td class="view"><%= link_to "View", order, class:"btn btn-outline-primary" %></td>
        <td class="finish"><%= link_to 'Finish', [order], remote: true, class:"btn btn-outline-danger", method: :put, data: { confirm: "Are you sure?" } %></th>
        <td class="cancel"><%= link_to 'Cancel', [order], remote: true, class:"btn btn-danger", method: :delete, data: { confirm: "Are you sure?" } %></th>
    <% else %>
        <td><%= link_to "View", order, class:"btn btn-outline-primary" %></td>
        <td class="finish"><button type="button" class="btn btn-outline-danger" disabled>Finish</button></th>
        <td class="cancel"><button type="button" class="btn btn-danger" disabled>Cancel</button></th>
    <% end %>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/orders/menu_img.html.erb
<div>
    <% if @order.menu_img.attached? %>
        <%= image_tag @order.menu_img, style: "width: 50%; display: block" %>
    <% end %>
</div>

app/views/orders/new.html.erb
<%= render "form", order: @order, friends_to_invite: @friends_to_invite %>

app/views/orders/order_Invited.html.erb
<div class="card mt-5">
  <div class="card-header text-center">
    <h3><i class="bi bi-person-lines-fill"></i> Invited Friends</h3>
  </div>
  <div class="card-body">
    <div class="row " style="top:0%, left:0%">
      <div class="col-md-10 row overflow-auto m-auto mt-5" id="friends-container" style="top: 0%; left: 0%; max-height: 350px;">
        <% if @invited_users.length == 0 %>
            <div class="alert alert-secondary text-center my-5" role="alert"style="width: 100%; " >
                There is NO pending invited friends !
            </div>
        <% else %>
            <% @invited_users.each do |invited_id| %>
                <div id = <%= invited_id.id %> class="col-md-4">
                    <div class="row" style="top:0%, left:0%">
                    <div class="card mx-5 my-3">
                        <div class="card-body">
                        <div class="col-md-6">
                            <%= image_tag invited_id.user.get_image, style: "height:120px;width:120;" %>
                        </div>
                        <div class="col-md-12">
                            <br>
                            <h4>
                            <div class="badge badge-light"> <%= invited_id.user.full_name %></div>
                            </h4>
                            <hr/>
                        <h6> <div class="btn btn-danger btn-sm">
                                <i class="bi bi-person-x"></i>
                                <%= link_to 'Remove', remove_invited_path(@order, invited_id), style: "color: white", remote: true, method: :get ,data: { confirm: "Are you sure?" } %>
                            </div>
                            </h6> 
                        </div>
                        </div>
                    </div>
                    </div>
                </div>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/orders/order_Joined.html.erb
<div class="card mt-5">
  <div class="card-header text-center">
    <h3><i class="bi bi-person-lines-fill"></i> Joined people</h3>
  </div>
  <div class="card-body">
    <div class="row " style="top:0%, left:0%">
      <div class="col-md-10 row overflow-auto m-auto mt-5" id="friends-container" style="top: 0%; left: 0%; max-height: 350px;">
        <% if @joined_users.length == 0 %>
            <div class="alert alert-secondary text-center my-5" role="alert"style="width: 100%; " >
                There is NO joined friends !
            </div>
        <% else %>
            <% @joined_users.each do |invited_id| %>
                <div id = <%= invited_id.id %> class="col-md-4">
                    <div class="row" style="top:0%, left:0%">
                    <div class="card mx-5 my-3">
                        <div class="card-body">
                        <div class="col-md-6">
                            <%= image_tag invited_id.user.get_image, style: "height:120px;width:120;" %>
                        </div>
                        <div class="col-md-12">
                            <br>
                            <h4>
                            <div class="badge badge-light"> <%= invited_id.user.full_name %></div>
                            </h4>
                            <hr/>
                        <h6> 
                            <%= link_to 'Remove', remove_joined_path(@order, invited_id), class:"btn btn-danger btn-sm", style: "color: white", remote: true, method: :get, data: { confirm: "Are you sure?" } %>
                            </h6> 
                        </div>
                        </div>
                    </div>
                    </div>
                </div>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<%################### ADD ITEMS ######################%>

<div class="card mt-4">
  <div class="card-header text-center">
        <h3>
          <i class="bi bi-card-text"></i> Order Details
        </h3>
    </div>
  <div class="card-body">
    <div class="row">
        <div class="col-7">
            <%  if @order.invited_members.where(joind: true).map(&:user_id).include? current_user.id or @order.user.id == current_user.id and @order.status == "Active" %>
                <div class="card">
                    <div class="card-body">
                        <%= render "form_item" %>
                    </div>
                </div>
            <% end %>
        </div>

        <% if current_user.id == @order.user_id %>
            <div class="col-5">
                <div class="card">
                    <div class="card-body">
                        <div class="card mt-4 border-primary">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-9">
                                        <%= @order.invited_members.where(joind: false).count %> Friends invited but not joined 
                                    </div>
                                    <div class="col-3">
                                        <%= link_to 'View', order_invited_path(@order), class:"btn btn-outline-primary" %>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card my-4 border-primary">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-9">
                                        <%= @order.invited_members.where(joind: true).count %> Friends joind 
                                    </div>
                                    <div class="col-3">
                                        <%= link_to 'View', order_joined_path(@order), class:"btn btn-outline-primary" %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <% else %>
            <img src="https://i.pinimg.com/originals/e4/4c/57/e44c577196d295eb166d7455078f5ca9.png" class="center m-auto" width="250" height="250">
        <% end %>
    </div>    
  </div>
</div>





<%################### TABLE ######################%>

<style>
  .thead-cusom
  {
    background-color: #FF5A01;
    color: white;
  }
</style>

<div class="card mt-2">
    <table class="table text-center ">
        <thead class="thead-cusom">
            <tr>
            <th scope="col">Person</th>
            <th scope="col">Item</th>
            <th scope="col">Amount</th>
            <th scope="col">Price</th>
            <th scope="col">Comment</th>
            <th scope="col" colspan="3">Action</th>
            </tr>
        </thead>
        <tbody id="items_table_body">
            <% @Items.each do |item| %>
                <tr id = "item_<%= item.id %>">
                    <td><%= item.user.full_name %></td>
                    <td><%= item.item %></td>
                    <td><%= item.amount %></td>
                    <td><%= item.price %></td>
                    <td><%= item.comment %></td>
                    <%  if item.user.id == current_user.id and @order.status == "Active" %>
                        <td><%= button_to 'Delete Item', [item.order, item], remote: true, class:"btn btn-danger btn-sm", method: :delete, data: { confirm: "Are you sure?" } %></td>
                    <% end %>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>