config/routes.rb
Rails.application.routes.draw do

  # * Friends controller routes without using resources

  # get "/friends/", to: "friends#index", as: "friends"
  # post "/friends/", to: "friends#create"
  # delete "/friends/:id", to: "friends#destroy", as: "friend"

  # * Generated Groups controller routes using resources

  # get 'groups/index'
  # get 'groups/new'
  # get 'groups/create'
  # get 'groups/destroy'
  # get 'groups/add_user'
  # get 'groups/create_user'
  # get 'groups/destroy_user'
  get "search_user_to_invite", to: "orders#search"
  get "add_user_to_invited_list", to: "orders#addToInvitedList"
  get "remove_user_from_invited_list", to: "orders#removeFromInvitedList"
  get "user_accepte_to_join_order", to: "orders#joinOrder"
  get "user_refuse_to_join_order", to: "orders#cancelInvitaion"
  # for invited and joined users
  get 'orders/:order_id/invited', :to => 'orders#order_Invited', as: "order_invited"
  get 'orders/:order_id/joined', :to => 'orders#order_Joined', as: "order_joined"
  get 'orders/:order_id/joined', :to => redirect('/order_joined.html.erb')
  get 'orders/:order_id/invited', :to => redirect('/order_invited.html.erb')

  # for removing users from order
  get 'orders/:order_id/joined/:invited_id', :to => 'orders#remove_Joined', as: "remove_joined"
  get 'orders/:order_id/invited/:invited_id', :to => 'orders#remove_Invited', as: "remove_invited"



  resources :friends
  resources :groups do
    get "/user", to: "groups#add_user", as: "add_user"
    post "/user", to: "groups#create_user", as: "create_user"
    delete "/user/:user_id", to: "groups#destroy_user", as: "destroy_user"
    get "search_user", to: "groups#search"
  end

  # * resource for notification
  resources :notifications

  # * resource for order
  resources :orders do
    resources :order_members
  end

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  authenticated :user do
    root "pages#home", as: "authenticated_root"
  end

  devise_scope :user do
    root "devise/sessions#new"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_alerts.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] %>
  </div>
<% elsif flash[:error] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:error] %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<style>
  .navbar-custom {
    background-color: #FF5A01;
  }
</style>

<% if user_signed_in? %>

  <nav class="navbar navbar-custom navbar-dark navbar-expand-sm" style="max-width: 100%">
    <div class="container-fluid">
      <a class="navbar-brand ml-5" href=<%= authenticated_root_path %>><b>Yalla</b>
        <img src="https://img.icons8.com/cute-clipart/2x/kawaii-pizza.png" width="55" height="55" alt="logo">
        <b>Notlob</b>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" >
        <span class="navbar-toggler-icon"></span>
      </button>

      <% # Dropdown %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav ml-5 mr-5">
          <li class="nav-item">
             <b><%= link_to "Orders", orders_path, class: "nav-link" %></b>
          </li>
          <li class="nav-item">
            <b><a class="nav-link" href=<%= authenticated_root_path %>>Menu</a></b>
          </li>
          <li class="nav-item">
            <b><%= link_to "Groups", groups_path, class: "nav-link" %></b>
          </li>
        </ul>

        <!-- <form class="form-inline ml-0 ">
          <input class="form-control mr-sm-2" type="search" placeholder="Search for orders..." aria-label="Search">
          <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
        </form> -->

        <%# <div class="container"></div> %>

    <%################################### Notifications #######################################%>

    <% new_notifications = current_user.receiver_notifications.where(viewed: false) %>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown mx-5">
            <a class="nav-link" href="#" id="billDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
              <% if new_notifications.count > 0 %>
                <h3 id="bell" class="bi bi-bell-fill" aria-hidden="true""></h3>
              <% else %>
                <h3 id="bell" class="bi bi-bell" aria-hidden="true"></h3>
            <% end %> 
            </a>
            <div class="dropdown-menu" aria-labelledby="billDropdown">
              
                <div class="notifications-container m-3">
                  <% new_notifications.each do |notification| %>
                    <div class="card">
                      <div class="card-body text-center">
                        <% if notification.notification_type == "invitation" %>
                        <a class="dropdown-item font-weight-bold " href="/notifications" data-seen="false" data-id="<%= notification.id %>"> <%= notification.sender.full_name %> Has Invited You to His Order<br/><br/> </a>

                          <%= notification.sender.full_name %> Has Invited You to His Order<br/><br/>
                          <%= link_to "Join", user_accepte_to_join_order_path(notification_id: notification.id, user: notification.receiver, order: notification.order), class: "btn btn-sm btn-success", method: :get %>
                          <%= link_to "Cancel", user_refuse_to_join_order_path(notification_id: notification.id, user: notification.receiver, order: notification.order), class: "btn btn-sm btn-danger", method: :get %>
                        <% else %>
                          <a class="dropdown-item font-weight-bold " href="/orders/<%= notification.order.id %>" data-seen="false" data-id="<%= notification.id %>"> <%= notification.sender.full_name %> Joined Your <%= notification.order.mealtype %> </a>
                        <% end %>
                      </div>  
                    </div>  
                    <hr/>
                  <% end %>
                </div>
             
              <div class="dropdown-divider"></div>
              <% if new_notifications.count == 0 %>
                <p id="no-new-notification" class="text-center"> No New Notifications </p>
                <div class="dropdown-divider"></div>
              <% end %>
              <a class="dropdown-item text-center" style="color: #FF5A01" href="/notifications">View All Notifications</a>
              
            </div>
          </li>
        </ul>
        <% # End Dropdown %>


      <%################################### Picture and Name #######################################%>

        <span class="nav-item " style="color: #ffff;">Welcome <%= current_user.full_name %> !</span>
        <ul class="navbar-nav ">
          <li class="nav-item dropdown mr-5">
            <a class="nav-link dropdown-toggle mr-5" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
              <img src="<%= current_user.get_image %>" width="50" height="50" class="rounded-circle">
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href=<%= authenticated_root_path %>>Dashboard</a>
              <a class="dropdown-item" href=<%= authenticated_root_path %>>Profile</a>
              <%= link_to "Friends", friends_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item", style: "color: red;" %>
            </div>
          </li>
        </ul>
      </div>
    </nav>
   
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yala Notlob</title>
    <link rel="icon" href="https://img.icons8.com/cute-clipart/2x/kawaii-pizza.png" type="image/png">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
          <%= render "layouts/alerts" %>

    <div class="container">
      <%= yield %>
    </div>
    <% if current_user %>
      <div id="user-id" data-user-id="<%= current_user.id %>"></div>
    <% end %>

    <%#= javascript_pack_tag 'notifications/notifications' %>
  </body>
</html>